name: Infrastructure Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Only trigger when terraform files change

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    
    # GLOBAL FIX: This sets the working directory for ALL steps in this job
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        
        env:
          TF_VAR_frontend_bucket_name: "starttech-frontend-prod-mercy-88" 
          # ^ Ensure this name is unique if you aren't using tfvars in CI
        run: terraform plan -no-color

      
